data = [
    {
        "name": "Christiano Ronaldo",
        "follower_count": 632.6,
        "description": "Footballer",
        "country": "Portugal"
    },
    {
        "name": "Leo Messi",
        "follower_count": 503.5,
        "description": "Footballer",
        "country": "Argentina",
    },
    {
        "name": "Selena Gomez",
        "follower_count": 	426.8,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Kylie Jenner",
        "follower_count": 399.1,
        "description": "Reality TV personality and business woman.",
        "country": "United States",
    },
    {
        "name": "Dwayne Johnson",
        "follower_count": 397,
        "description": "Actor and professional wrestler",
        "country": "United States",
    },
    {
        "name": "Ariana Grande",
        "follower_count": 378.7,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Kim Kardashian",
        "follower_count": 362.1,
        "description": "Reality TV personality and business woman.",
        "country": "United States",
    },
    {
        "name": "Beyonce",
        "follower_count": 318.2,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Khloe Kardashian",
        "follower_count": 308.6,
        "description": "Reality TV personality and business woman.",
        "country": "United States",
    },
    {
        "name": "Nike",
        "follower_count": 305.9,
        "description": "Sports company",
        "country": "United States",
    },
    {
        "name": "Justin Bieber",
        "follower_count": 293.4,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Kendall Jenner",
        "follower_count": 293,
        "description": "Reality TV personality and business woman.",
        "country": "United States",
    },
    {
        "name": "Taylor Swift",
        "follower_count": 283.7,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Virat Kohli",
        "follower_count": 269.2,
        "description": "Cricketer",
        "country": "India",
    },
    {
        "name": "Jennifer Lopez",
        "follower_count": 252.3,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Nicki Minaj",
        "follower_count": 227990090,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Kourtney Kardashian",
        "follower_count": 223.1,
        "description": "American media personality and socialite.",
        "country": "United States",
    },
    {
        "name": "Neymar da Silva Santos Jr",
        "follower_count": 222.2,
        "description": "Footballer",
        "country": "Brazil",
    },
    {
        "name": "Miley Cyrus",
        "follower_count": 215,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Katy Perry",
        "follower_count": 206.6,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Zendaya",
        "follower_count": 183.86,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Kevin Hart",
        "follower_count": 179.8,
        "description": "Actor and comedian",
        "country": "United States",
    },
    {
        "name": "Cardi B",
        "follower_count": 176.1,
        "description": "Musician and female rapper",
        "country": "United States",
    },
    {
        "name": "Demi Lovato",
        "follower_count": 156.2,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Billie Eilish",
        "follower_count": 119.3,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Gal Gadot",
        "follower_count": 108.7,
        "description": "Actress",
        "country": "Israel",
    },
    {
        "name": "Vin Diesel",
        "follower_count": 102.8,
        "description": "Actor",
        "country": "United States",
    },
    {
        "name": "Shakira",
        "follower_count": 90.5,
        "description": "Musician",
        "country": "Colombia",
    },
    {
        "name": "Dua Lipa",
        "follower_count": 88.1,
        "description": "Musician",
        "country": "British",
    },
    {
        "name": "David Beckam",
        "follower_count": 88,
        "description": "Musician",
        "country": "British",
    },
    {
        "name": "Snoop Dogg",
        "follower_count": 87.6,
        "description": "Musician",
        "country": "British",
    },
]
